In [ ]:
#!wget https://raw.githubusercontent.com/tripathysagar/ODIA_HUMAN_NUMBER/main/odia_digits.csv

--2022-09-06 06:01:18--  https://raw.githubusercontent.com/tripathysagar/ODIA_HUMAN_NUMBER/main/odia_digits.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1025379 (1001K) [text/plain]
Saving to: ‘odia_digits.csv’

odia_digits.csv     100%[===================>]   1001K  --.-KB/s    in 0.05s   

2022-09-06 06:01:18 (20.6 MB/s) - ‘odia_digits.csv’ saved [1025379/1025379]



In [2]:
from fastai.text.all import *
from fastai.imports import *

In [3]:
Path().ls()

(#3) [Path('00.ipynb'),Path('odia_digits.csv'),Path('.ipynb_checkpoints')]

In [4]:
df = pd.read_csv(Path('odia_digits.csv'), low_memory=False)
df.head()

0    1    2     3     4      5     6     7     8    9  ...  \
0      ୦    ୧    ୨     ୩     ୪      ୫     ୬     ୭     ୮    ୯  ...   
1  ଶୁନ୍ୟ   ଏକ  ଦୁଇ  ତିନି  ଚାରି  ପାଞ୍ଚ    ଛଅ   ସାତ    ଆଠ   ନଅ  ...   
2  śunẏa  eka  dui  tini  cāri  pāṅca  chaa  sāta  āṭha  naa  ...   

                10091                10092                10093  \
0               ୧୦୦୯୧                ୧୦୦୯୨                ୧୦୦୯୩   
1      ଦଶ ହଜାର ଏକାନବେ       ଦଶ ହଜାର ବୟାନବେ      ଦଶ ହଜାର ତେୟାନବେ   
2  daśa hajār ekānabe  daśa hajār baẏānabe  daśa hajār teẏānabe   

                  10094                 10095                 10096  \
0                 ୧୦୦୯୪                 ୧୦୦୯୫                 ୧୦୦୯୬   
1       ଦଶ ହଜାର ଚଉରାନବେ      ଦଶ ହଜାର ପଞ୍ଚାନବେ        ଦଶ ହଜାର ଛୟାନବେ   
2  daśa hajār caurānabe  daśa hajār paṅcānabe  daśa hajār chaẏānabe   

                 10097                10098               10099  \
0                ୧୦୦୯୭                ୧୦୦୯୮               ୧୦୦୯୯   
1       ଦଶ ହଜାର ସତାନବେ       ଦଶ ହଜାର ଅଠାନବେ       ଦଶ ହଜାର ଅନେଶତ   
2  daśa hajār satānabe  daśa hajār aṭhānabe  daśa hajār aneśata   

             10100  
0            ୧୦୧୦୦  
1      ଦଶ ହଜାର ଶହେ  
2  daśa hajār śahe  

[3 rows x 10103 columns]

In [5]:
txt = L(df.iloc[1].tolist())

In [6]:
txt

(#10103) ['ଶୁନ୍ୟ','ଏକ','ଦୁଇ','ତିନି','ଚାରି','ପାଞ୍ଚ','ଛଅ','ସାତ','ଆଠ','ନଅ'...]

In [7]:
txt[1000]

'ନଅ ଶହ ସତାନବେ'

In [8]:
text = ' . '.join([l.strip() for l in txt])
text[:100]

'ଶୁନ୍ୟ . ଏକ . ଦୁଇ . ତିନି . ଚାରି . ପାଞ୍ଚ . ଛଅ . ସାତ . ଆଠ . ନଅ . ଦଶ . ଏଗାର . ବାର . ତେର . ଚଉଦ . ପନ୍ଦର . '

Now we need to tokenize the text

In [9]:
tokens = text.split(' ')
tokens[:10]

['ଶୁନ୍ୟ', '.', 'ଏକ', '.', 'ଦୁଇ', '.', 'ତିନି', '.', 'ଚାରି', '.']

We need to fetch all the unique words 

In [10]:
vocab = L(*tokens).unique()
vocab

(#106) ['ଶୁନ୍ୟ','.','ଏକ','ଦୁଇ','ତିନି','ଚାରି','ପାଞ୍ଚ','ଛଅ','ସାତ','ଆଠ'...]

Convert each tokens to numbers

In [11]:
word2idx = {w:i for i,w in enumerate(vocab)}

nums = L(word2idx[w] for w in tokens)
nums

(#54307) [0,1,2,1,3,1,4,1,5,1...]

In [12]:
len(tokens), len(txt)

(54307, 10103)

## Model from scratch

In [13]:
def group_chunks(ds, bs):
    m = len(ds) // bs
    new_ds = L()
    for i in range(m): new_ds += L(ds[i + m*j] for j in range(bs))
    return new_ds

In [14]:
sl = 16
bs = 64
seqs = L((tensor(nums[i:i+sl]), tensor(nums[i+1:i+sl+1]))
         for i in range(0,len(nums)-sl-1,sl))
cut = int(len(seqs) * 0.8)
dls = DataLoaders.from_dsets(group_chunks(seqs[:cut], bs),
                             group_chunks(seqs[cut:], bs),
                             bs=bs, drop_last=True, shuffle=False)

In [15]:
seqs[0]

(tensor([0, 1, 2, 1, 3, 1, 4, 1, 5, 1, 6, 1, 7, 1, 8, 1]),
 tensor([1, 2, 1, 3, 1, 4, 1, 5, 1, 6, 1, 7, 1, 8, 1, 9]))

In [16]:
x,y = dls.train.one_batch()

In [17]:
x[0],y[0]

(tensor([0, 1, 2, 1, 3, 1, 4, 1, 5, 1, 6, 1, 7, 1, 8, 1]),
 tensor([1, 2, 1, 3, 1, 4, 1, 5, 1, 6, 1, 7, 1, 8, 1, 9]))

In [18]:
class LMModel1(Module):
    def __init__(self, vocab_sz, n_hidden):
        self.i_h = nn.Embedding(vocab_sz, n_hidden)  
        self.h_h = nn.Linear(n_hidden, n_hidden)     
        self.h_o = nn.Linear(n_hidden,vocab_sz)
        self.h = 0
        
    def forward(self, x):
        outs = []
        for i in range(sl):
            self.h = self.h + self.i_h(x[:,i])
            self.h = F.relu(self.h_h(self.h))
            outs.append(self.h_o(self.h))
        self.h = self.h.detach()
        return torch.stack(outs, dim=1)
    
    def reset(self): self.h = 0

In [19]:
model =  LMModel1(len(vocab), 64)

In [20]:
model

LMModel4(
  (i_h): Embedding(106, 64)
  (h_h): Linear(in_features=64, out_features=64, bias=True)
  (h_o): Linear(in_features=64, out_features=106, bias=True)
)

In [21]:
ypred = model(x)
ypred.shape

torch.Size([64, 16, 106])

In [22]:
ypred.view(-1, len(vocab)).shape,y.view(-1).shape

(torch.Size([1024, 106]), torch.Size([1024]))

In [23]:

def loss_func(inp, targ):
    return F.cross_entropy(inp.view(-1, len(vocab)), targ.view(-1))

In [24]:
learn = Learner(dls, LMModel1(len(vocab), 64), loss_func=loss_func,
                metrics=accuracy, cbs=ModelResetter)
learn.fit_one_cycle(12, 3e-3)

## using RNN

In [63]:
class LMModel2(Module):
    def __init__(self, vocab_sz, n_hidden, n_layers):
        self.i_h = nn.Embedding(vocab_sz, n_hidden)
        self.rnn = nn.RNN(n_hidden, n_hidden, n_layers, batch_first=True)
        self.h_o = nn.Linear(n_hidden, vocab_sz)
        self.h = torch.zeros(n_layers, bs, n_hidden)
        
    def forward(self, x):
        res,h = self.rnn(self.i_h(x), self.h)
        self.h = h.detach()
        return self.h_o(res)
    
    def reset(self): self.h.zero_()

In [64]:
learn = Learner(dls, LMModel2(len(vocab), 64, 2), 
                loss_func=CrossEntropyLossFlat(), 
                metrics=accuracy, cbs=ModelResetter)
learn.fit_one_cycle(15, 3e-3)

## Using LSTM cell


In [27]:
emb = nn.Embedding(len(vocab), 64)

In [28]:
emb(x).shape

torch.Size([64, 16, 64])

In [29]:
len([torch.zeros(10,10) for _ in range(2)])

2

In [71]:
class LMModel3(Module):
    def __init__(self, vocab_sz, n_hidden, n_layers):
        self.ih = nn.Embedding(vocab_sz, n_hidden)
        self.rnn = nn.LSTM(n_hidden, n_hidden, n_layers, batch_first = True)
        self.ho = nn.Linear(n_hidden, vocab_sz)
        self.h = [torch.zeros(n_layers, bs, n_hidden) for _ in range(n_layers)]
    
    def forward(self, x):
        res, h = self.rnn(self.ih(x), self.h) # returns resedual and hidden state
        #print(res.shape)
        self.h = [h_.detach() for h_ in h]  # delete the derivative part
        
        
        return self.ho(res)
    
    def reset(self):
        for h in self.h: h.zero_()
    

In [72]:
model = LMModel3(len(vocab), 64, 2)
model

LMModel3(
  (ih): Embedding(106, 64)
  (rnn): LSTM(64, 64, num_layers=2, batch_first=True)
  (ho): Linear(in_features=64, out_features=106, bias=True)
)

In [73]:
x.shape, y.shape

(torch.Size([64, 16]), torch.Size([64, 16]))

In [74]:
model(x).shape

torch.Size([64, 16, 106])

In [75]:
learn = Learner(dls, LMModel3(len(vocab), 64, 2), 
                loss_func=CrossEntropyLossFlat(), 
                metrics=accuracy, cbs=ModelResetter)
learn.fit_one_cycle(15, 1e-2)

In [35]:
z = torch.randn(4,5)
z

tensor([[ 0.6994, -0.0688, -0.6969, -1.2239,  0.9241],
        [ 0.4317, -0.3241,  0.7665,  1.2448,  1.1512],
        [ 0.4410, -0.9058,  1.2183, -0.5550,  1.4103],
        [ 0.4232,  1.0480,  0.4265, -0.8930, -0.6336]])

In [36]:
zp = z.new(z.shape)

In [37]:
zp

tensor([[-1.8320e-18,  4.5584e-41,  1.6375e-22,  3.0645e-41,  1.4013e-45],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  2.2813e-22,  3.0645e-41,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  2.8026e-45,  0.0000e+00]])

In [38]:
zpp = z.new(z.shape).bernoulli_(0.8)

In [39]:
zpp

tensor([[1., 1., 0., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 0., 1.]])

In [40]:
z * zpp

tensor([[ 0.6994, -0.0688, -0.0000, -1.2239,  0.9241],
        [ 0.4317, -0.3241,  0.7665,  1.2448,  1.1512],
        [ 0.4410, -0.9058,  1.2183, -0.5550,  1.4103],
        [ 0.4232,  1.0480,  0.4265, -0.0000, -0.6336]])

## LSTM with dropout

In [76]:
class Dropout(Module):
    def __init__(self, p):
        self.p = p
    
    def forward(self,x):
        if not self.training:
            return x
        
        mask = x.new(x.shape).bernoulli_(1-self.p)
        return x * mask.div_(1-self.p)

In [77]:
class LMModel4(Module):
    def __init__(self, vocab_sz, n_hidden, n_layers, p):
        self.ih = nn.Embedding(vocab_sz, n_hidden)
        self.rnn = nn.LSTM(n_hidden, n_hidden, n_layers, batch_first = True)
        self.ho = nn.Linear(n_hidden, vocab_sz)
        self.h = [torch.zeros(n_layers, bs, n_hidden) for _ in range(n_layers)]
        
        self.drop = Dropout(p)
    
    def forward(self, x):
        res, h = self.rnn(self.ih(x), self.h) # returns resedual and hidden state
        #print(res.shape)
        res = self.drop(res)
        self.h = [h_.detach() for h_ in h]  # delete the derivative part
        
        
        return self.ho(res)
    
    def reset(self):
        for h in self.h: h.zero_()
    

In [79]:
learn = Learner(dls, LMModel4(len(vocab), 64, 2, .5), 
                loss_func=CrossEntropyLossFlat(), 
                metrics=accuracy, cbs=ModelResetter)
learn.fit_one_cycle(15, 1e-2)

## Weight tied LSTM with dropout

In [80]:
class LMModel5(Module):
    def __init__(self, vocab_sz, n_hidden, n_layers, p):
        self.ih = nn.Embedding(vocab_sz, n_hidden)
        self.rnn = nn.LSTM(n_hidden, n_hidden, n_layers, batch_first = True)
        self.ho = nn.Linear(n_hidden, vocab_sz)
        self.h = [torch.zeros(n_layers, bs, n_hidden) for _ in range(n_layers)]
        self.ho.weight = self.ih.weight
        self.drop = Dropout(p)
    
    def forward(self, x):
        res, h = self.rnn(self.ih(x), self.h) # returns resedual and hidden state
        #print(res.shape)
        res = self.drop(res)
        self.h = [h_.detach() for h_ in h]  # delete the derivative part
        
        
        return self.ho(res)
    
    def reset(self):
        for h in self.h: h.zero_()
    

In [81]:
learn = Learner(dls, LMModel5(len(vocab), 64, 2, .5), 
                loss_func=CrossEntropyLossFlat(), 
                metrics=accuracy, cbs=ModelResetter)
learn.fit_one_cycle(12, 1e-2)

## Weight tied LSTM with dropout and Regularization

In [113]:
class LMModel6(Module):
    def __init__(self, vocab_sz, n_hidden, n_layers, p):
        self.ih = nn.Embedding(vocab_sz, n_hidden)
        self.rnn = nn.LSTM(n_hidden, n_hidden, n_layers, batch_first = True)
        
        self.drop = Dropout(p)
        
        self.ho = nn.Linear(n_hidden, vocab_sz)
        self.ho.weight = self.ih.weight
        self.h = [torch.zeros(n_layers, bs, n_hidden) for _ in range(n_layers)]
        
        
    
    def forward(self, x):
        raw,h = self.rnn(self.ih(x), self.h)
        out = self.drop(raw)
        self.h = [h_.detach() for h_ in h]
        return self.ho(out),raw,out
        
        
    
    def reset(self):
        for h in self.h: h.zero_()
    

In [114]:
learn = TextLearner(dls, LMModel6(len(vocab), 64, 2, 0.4),
                    loss_func=CrossEntropyLossFlat(), metrics=accuracy)

In [115]:
learn.fit_one_cycle(15, 1e-2, wd=0.1)

### Conclusion

The 6th model works well wrt all the other model.